1
Signed-off-by: havario <157877551+havario@users.noreply.github.com>

diff --git a/.github/workflows/3x-ui.yaml b/.github/workflows/3x-ui.yaml
--- a/.github/workflows/3x-ui.yaml
+++ b/.github/workflows/3x-ui.yaml
@@ -22,49 +22,82 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+env:
+  DOCKERHUB_REPO: ${{ secrets.DOCKER_USERNAME }}/3x-ui
+
 jobs:
-  release:
-    name: "Build binary"
+  check:
+    name: "Pre check"
     runs-on: ubuntu-latest
+    outputs:
+      renew: ${{ steps.vers.outputs.renew }}
+      xray_version: ${{ steps.vers.outputs.xray_version }}
+      xui_tag: ${{ steps.vers.outputs.xui_tag }}
+
+    steps:
+      - name: "Fetch Versions and Decide"
+        id: vers
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          set -eEuxo pipefail
+          RENEW="false"
+          XRAY_TAG="$(gh release view -R XTLS/Xray-core --json tagName -q .tagName)"
+          XRAY_VER=${XRAY_TAG#v}
+          XUI_TAG="$(gh release view -R MHSanaei/3x-ui --json tagName -q .tagName)"
+          XUI_VER=${XUI_TAG#v}
+          CURRENT_VER="$(skopeo list-tags "docker://docker.io/$DOCKERHUB_REPO" 2>/dev/null | jq -r '.Tags[] | select(. != "latest")' | sort -rV | head -n 1 || true)"
+          if [[ "$(printf '%s\n%s\n' "$XUI_VER" "$CURRENT_VER" | sort -V | head -n 1)" != "$XUI_VER" ]] || [[ -z "$CURRENT_VER" && -n "$XUI_VER" ]]; then
+            echo "Build required."
+            RENEW="true"
+          fi
+          echo "renew=${RENEW}" >> "$GITHUB_OUTPUT"
+          echo "xray_version=${XRAY_VER}" >> "$GITHUB_OUTPUT"
+          echo "xui_tag=${XUI_TAG}" >> "$GITHUB_OUTPUT"
+
+  build:
+    name: "Build image"
+    runs-on: ubuntu-latest
+    needs: [check]
     strategy:
       fail-fast: true
       matrix:
-        include:
-          - { goos: linux, goarch: "386", platform: "linux/386" }
-          - { goos: linux, goarch: amd64, platform: "linux/amd64" }
-          - { goos: linux, goarch: arm, goarm: "6", platform: "linux/arm/v6" }
-          - { goos: linux, goarch: arm, goarm: "7", platform: "linux/arm/v7" }
-          - { goos: linux, goarch: arm64, platform: "linux/arm64" }
-          - { goos: linux, goarch: ppc64le, platform: "linux/ppc64le" }
-          - { goos: linux, goarch: riscv64, platform: "linux/riscv64" }
-          - { goos: linux, goarch: s390x, platform: "linux/s390x" }
-    env:
-      GOOS: ${{ matrix.goos }}
-      GOARCH: ${{ matrix.goarch }}
-      GOARM: ${{ matrix.goarm }}
-      CGO_ENABLED: 1
+        platform:
+          - linux/386
+          - linux/amd64
+          - linux/arm/v6
+          - linux/arm/v7
+          - linux/arm64
+          - linux/ppc64le
+          - linux/riscv64
+          - linux/s390x
 
     steps:
       - name: "Checkout repository"
         uses: actions/checkout@v6
 
-      - name: "Clone source code"
+      - name: "Prepare"
+        run: |
+          PLATFORM_PAIR=$(awk -F/ '{print $1"-"$2$3}' <<< "${{ matrix.platform }}")
+          echo "PLATFORM_PAIR=$PLATFORM_PAIR" >> "$GITHUB_ENV"
+
+      - name: "Download geodat"
         working-directory: core/3x-ui
-        run: git clone --depth=1 --branch v2.8.7 https://github.com/MHSanaei/3x-ui.git src
-
-      - name: "Setup Go"
-        uses: actions/setup-go@v6
-        with:
-          go-version-file: core/3x-ui/src/go.mod
-          check-latest: true
-
-      - name: "Download gomod"
-        working-directory: core/3x-ui/src
-        run: go mod download
-
-      - name: "Build 3x-ui binary"
-        working-directory: core/3x-ui/src
         run: |
           set -eEuxo pipefail
-          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM"
-          go build -v -o x-ui -ldflags="-s -w -linkmode external -extldflags '-static' -buildid=" ./main.go
+          declare -a GEO_FILES=("geoip" "geosite")
+          for GEO_FILE in "${GEO_FILES[@]}"; do
+            curl -L -O "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/$GEO_FILE.dat"
+            curl -L -O "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/$GEO_FILE.dat.sha256sum"
+            sha256sum -c "$GEO_FILE.dat.sha256sum"
+          done
+          for GEO_FILE in "${GEO_FILES[@]}"; do
+            curl -L -O "https://github.com/chocolate4u/Iran-v2ray-rules/releases/latest/download/$GEO_FILE.dat"
+            curl -L -O "https://github.com/chocolate4u/Iran-v2ray-rules/releases/latest/download/$GEO_FILE.dat.sha256sum"
+            sha256sum -c "$GEO_FILE.dat.sha256sum"
+          done
+          for GEO_FILE in "${GEO_FILES[@]}"; do
+            curl -L -O "https://github.com/runetfreedom/russia-v2ray-rules-dat/releases/latest/download/$GEO_FILE.dat"
+            curl -L -O "https://github.com/runetfreedom/russia-v2ray-rules-dat/releases/latest/download/$GEO_FILE.dat.sha256sum"
+            sha256sum -c "$GEO_FILE.dat.sha256sum"
+          done
